---
spec:
  template:
    spec:
      containers:
      - env:
        - name: SERVER_LIST
          valueFrom:
            secretKeyRef:
              name: "${fabric8-maven-plugin.secret-name}"
              key: "infinispan.client.hotrod.server_list"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: "${fabric8-maven-plugin.secret-name}"
              key: "infinispan.client.hotrod.auth_username"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: "${fabric8-maven-plugin.secret-name}"
              key: "infinispan.client.hotrod.auth_password"
        name: "${project.artifactId}"
        ports:
        - containerPort: 8778
          name: jolokia-port
          protocol: TCP
